language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t varsha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true varsha/docker-react npm run test -- --coverage